version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/sites-enabled/default
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root #PRODUCTION: the user should be different from root with access restrictions
      DB_PASSWORD: MySuperStrongPassword
    networks:
      - web_network


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MySuperStrongPassword
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - web_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - web_network

volumes:
  redis_data:
  dbdata:

networks:
  web_network:
    driver: bridge
